"""add group_ref to orders and loans

Revision ID: 93c222e46929
Revises: e618aced3485
Create Date: 2026-06-27 11:20:28.875261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c222e46929'
down_revision: Union[str, Sequence[str], None] = 'e618aced3485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_ref', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_loans_group_ref'), ['group_ref'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_ref', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_group_ref'), ['group_ref'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_group_ref'))
        batch_op.drop_column('group_ref')

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loans_group_ref'))
        batch_op.drop_column('group_ref')

    # ### end Alembic commands ###
